### PR TITLE
Question page

### PR DESCRIPTION
**Pull request by ds161833**
Okay so the structure is kinda reADY DON;T LOOK at the awful design it will be fixed larter, pls review

### CODE REVIEW

**Review by Tripe2000 — APPROVED** [review]
I approve. Good work, nice and working code

**Comment by irinafrazao** [comment]
Like\Dislike buttons are nice. Need to look like the rest of the website.

**Review by irinafrazao — APPROVED** [review]
Like\Dislike buttons are nice. Need to look like the rest of the website.

**Review by tongweiz — APPROVED** [review]
It works. Approved.

**Pull request merged**
